server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./kgd
    username: usr
    password: pwd
  jpa:
    open-in-view: false
    show-sql: false
    #show-sql: true
    hibernate:
      ddl-auto: none
      #ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    ru.igorit.andrk: DEBUG
    #ru.igorit.andrk: TRACE
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
